import { createFileRoute } from "@tanstack/react-router";
import { Activity, ArrowRight, BatteryCharging, CheckCircle2, ChevronRight, CloudCog, Cpu, Gauge, Menu, Network, PlugZap, Radio, Route as RouteIcon, ShieldCheck, Signal, Sun, TrafficCone, X, Zap, type LucideIcon } from "lucide-react";
import { useEffect, useState } from "react";
import logoAsset from "../assets/rik-logo.svg.asset.json";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "RIK Serviss | Smart Infrastructure Platform" },
    { name: "description", content: "RIK builds connected safety infrastructure and centralized monitoring for cities and road authorities." },
    { property: "og:title", content: "RIK Serviss | Smart Infrastructure Platform" },
    { property: "og:description", content: "Connected hardware and centralized monitoring for modern roads and cities." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: Index,
});

type Lang = "lv" | "en" | "ru";
const en = {
  nav:["Platform","First solution","Applications","Monitoring"], contact:"Start a conversation", open:"Open menu", close:"Close menu",
  heroTag:"Connected · Flexible · Built for the real world", heroA:"Infrastructure that", heroB:"sees, thinks", heroC:"and acts.", heroText:"RIK builds connected safety systems that bring field infrastructure into one intelligent platform.", explore:"Explore the platform", first:"See our first solution", built:"Built for", audiences:["Cities","Road authorities","Infrastructure operators"], scroll:"Scroll to explore",
  network:"Network live", nodes:"4 nodes connected", lora:"LoRa network", long:"Long-range connection", power:"Flexible power", powerModes:"Grid · solar · hybrid", uptime:"fleet uptime",
  platformTag:"The RIK platform", platformTitle:"One system.|Four connected layers.", platformText:"We unite rugged field hardware, flexible power architecture, low-power connectivity, and fleet intelligence into one deployable platform.",
  layers:[
    ["Edge sensing","Purpose-built sensors detect events locally with speed and precision."],
    ["Flexible power","Designed for full electrical connection, solar, battery, or hybrid power according to each site."],
    ["LoRa connectivity","Resilient, long-range communication designed for distributed infrastructure."],
    ["Central monitoring","Every deployed asset reports health, events, and performance to one view."],
  ], flow:["Detect","Act","Connect","Understand"],
  solutionTag:"Our first deployed solution", solutionTitle:"A safer crossing that thinks for itself.", solutionText:"RIK’s smart pedestrian crossing detects people at the roadside, activates high-visibility warning signals, and reports every event. Power and connectivity are configured for the needs of each location.", checks:["Installation adapted to each site","Reliable operation through northern winters","Remote health and performance visibility"], discuss:"Discuss a deployment", active:"Active event", detected:"Pedestrian detected · Beacons engaged", metrics:[["< 1 sec","event response"],["24 / 7","remote visibility"],["Flexible","power options"]],
  productsTag:"A growing product portfolio", productsTitle:"The crossing is the beginning,|not the boundary.", productsText:"RIK is a platform company. New connected products can share the same sensing, communications, and monitoring foundation.", current:"Deployed now", crossing:"Smart pedestrian crossing", crossingText:"Active roadside detection and high-visibility warning for safer crossings.", future:"Future product space", futureText:"Reserved for the next RIK infrastructure solution.",
  appsTag:"Designed to extend", appsTitle:"One platform. More|ways to make cities safer.", apps:[["Roadworks & temporary zones","Rapid-deploy warning systems for changing road conditions."],["Traffic flow intelligence","Distributed sensing for better-informed mobility decisions."],["Perimeter & public safety","Connected monitoring for critical public spaces."],["Environmental monitoring","Remote measurement networks for air, noise, and local conditions."]],
  monitorTag:"Centralized intelligence", monitorTitle:"Know what’s happening.|Before it becomes a problem.", monitorText:"RIK Command brings every connected asset into one operational view—from power health and signal quality to event history and maintenance needs.", points:[["Live fleet status","See every site at a glance"],["Predictive maintenance","Act before service is interrupted"],["Evidence & reporting","Turn field activity into insight"]], overview:"Network overview", region:"Riga region", update:"Last update: now", activeDevices:"Active devices", thisWeek:"+2 this week", powerHealth:"Power health", healthy:"Healthy", events:"Events today", siteHealth:"Site health", online:"Online", check:"Check", live:"Live",
  contactTag:"Build with RIK", contactTitle:"Infrastructure should be|intelligent by default.", contactText:"Let’s explore where connected infrastructure can make the greatest difference in your network.", footer:"Connected intelligence for safer infrastructure.",
};
type Copy = typeof en;
const copy: Record<Lang, Copy> = {
  en,
  lv: {
    nav:["Platforma","Pirmais risinājums","Pielietojumi","Uzraudzība"], contact:"Sākt sarunu", open:"Atvērt izvēlni", close:"Aizvērt izvēlni",
    heroTag:"Savienota · Elastīga · Radīta reālai videi", heroA:"Infrastruktūra, kas", heroB:"redz, domā", heroC:"un rīkojas.", heroText:"RIK veido savienotas drošības sistēmas, kas apvieno fizisko infrastruktūru vienotā viedā platformā.", explore:"Izpētīt platformu", first:"Apskatīt pirmo risinājumu", built:"Radīts", audiences:["Pilsētām","Ceļu pārvaldītājiem","Infrastruktūras operatoriem"], scroll:"Ritiniet, lai izpētītu",
    network:"Tīkls darbojas", nodes:"Savienoti 4 mezgli", lora:"LoRa tīkls", long:"Liela darbības attāluma savienojums", power:"Elastīga barošana", powerModes:"Tīkls · saule · hibrīds", uptime:"tīkla darbspēja",
    platformTag:"RIK platforma", platformTitle:"Viena sistēma.|Četri savienoti slāņi.", platformText:"Mēs apvienojam izturīgu lauka aparatūru, elastīgu barošanu, zema patēriņa savienojamību un centralizētu pārvaldību vienā platformā.",
    layers:[["Lokālā uztveršana","Specializēti sensori ātri un precīzi nosaka notikumus uz vietas."],["Elastīga barošana","Pilns elektrības pieslēgums, saules, akumulatoru vai hibrīda risinājums atbilstoši objektam."],["LoRa savienojums","Uzticama liela attāluma saziņa izkliedētai infrastruktūrai."],["Centralizēta uzraudzība","Katrs objekts vienuviet ziņo par stāvokli, notikumiem un veiktspēju."]], flow:["Noteikt","Rīkoties","Savienot","Izprast"],
    solutionTag:"Mūsu pirmais ieviestais risinājums", solutionTitle:"Drošāka pāreja, kas domā pati.", solutionText:"RIK viedā gājēju pāreja nosaka cilvēkus ceļa malā, aktivizē labi pamanāmus brīdinājuma signālus un reģistrē katru notikumu. Barošana un sakari tiek pielāgoti katrai vietai.", checks:["Uzstādīšana pielāgota katram objektam","Uzticama darbība ziemeļu ziemās","Attālināta stāvokļa un veiktspējas pārraudzība"], discuss:"Apspriest ieviešanu", active:"Aktīvs notikums", detected:"Gājējs noteikts · Signāli ieslēgti", metrics:[["< 1 sek.","reakcijas laiks"],["24 / 7","attālināta redzamība"],["Elastīga","barošanas izvēle"]],
    productsTag:"Augošs produktu portfelis", productsTitle:"Pāreja ir sākums,|nevis robeža.", productsText:"RIK ir platformas uzņēmums. Jauni savienoti produkti var izmantot to pašu sensoru, sakaru un uzraudzības pamatu.", current:"Ieviests", crossing:"Viedā gājēju pāreja", crossingText:"Aktīva ceļmalas noteikšana un labi pamanāmi brīdinājumi drošākām pārejām.", future:"Vieta nākamajam produktam", futureText:"Rezervēts nākamajam RIK infrastruktūras risinājumam.",
    appsTag:"Radīta paplašināšanai", appsTitle:"Viena platforma. Vairāk|iespēju drošākām pilsētām.", apps:[["Ceļu darbi un pagaidu zonas","Ātri izvietojamas brīdinājuma sistēmas mainīgiem ceļa apstākļiem."],["Satiksmes plūsmas analītika","Izkliedēti sensori labākiem mobilitātes lēmumiem."],["Perimetra un sabiedriskā drošība","Savienota kritisku publisko vietu uzraudzība."],["Vides monitorings","Attālināti gaisa, trokšņa un vietējo apstākļu mērījumu tīkli."]],
    monitorTag:"Centralizēta informācija", monitorTitle:"Ziniet, kas notiek.|Pirms rodas problēma.", monitorText:"RIK Command apvieno visus savienotos objektus vienā skatā — no barošanas un signāla kvalitātes līdz notikumu vēsturei un apkopei.", points:[["Tīkla statuss reāllaikā","Pārskatiet katru objektu"],["Prognozējoša apkope","Rīkojieties pirms darbības pārtraukuma"],["Dati un atskaites","Pārvērtiet notikumus noderīgā informācijā"]], overview:"Tīkla pārskats", region:"Rīgas reģions", update:"Atjaunināts: tagad", activeDevices:"Aktīvās ierīces", thisWeek:"+2 šonedēļ", powerHealth:"Barošanas stāvoklis", healthy:"Labs", events:"Notikumi šodien", siteHealth:"Objektu stāvoklis", online:"Tiešsaistē", check:"Pārbaudīt", live:"Tiešraide",
    contactTag:"Veidojiet ar RIK", contactTitle:"Infrastruktūrai jābūt|viedai pēc noklusējuma.", contactText:"Izpētīsim, kur savienota infrastruktūra var sniegt lielāko ieguvumu jūsu tīklam.", footer:"Savienota inteliģence drošākai infrastruktūrai.",
  },
  ru: {
    nav:["Платформа","Первое решение","Применение","Мониторинг"], contact:"Начать разговор", open:"Открыть меню", close:"Закрыть меню",
    heroTag:"Связано · Гибко · Создано для реального мира", heroA:"Инфраструктура, которая", heroB:"видит, думает", heroC:"и действует.", heroText:"RIK создаёт подключённые системы безопасности, объединяющие физическую инфраструктуру на единой интеллектуальной платформе.", explore:"Изучить платформу", first:"Первое решение", built:"Создано для", audiences:["Городов","Дорожных служб","Операторов инфраструктуры"], scroll:"Прокрутите, чтобы изучить",
    network:"Сеть работает", nodes:"Подключено 4 узла", lora:"Сеть LoRa", long:"Связь большого радиуса", power:"Гибкое питание", powerModes:"Сеть · солнце · гибрид", uptime:"доступность сети",
    platformTag:"Платформа RIK", platformTitle:"Одна система.|Четыре связанных уровня.", platformText:"Мы объединяем надёжное полевое оборудование, гибкую архитектуру питания, энергоэффективную связь и управление сетью в одной платформе.",
    layers:[["Локальные датчики","Специализированные датчики быстро и точно определяют события на месте."],["Гибкое питание","Полное электроподключение, солнечное, аккумуляторное или гибридное питание под каждый объект."],["Связь LoRa","Надёжная связь большого радиуса для распределённой инфраструктуры."],["Центральный мониторинг","Каждый объект передаёт состояние, события и показатели в единый интерфейс."]], flow:["Обнаружить","Действовать","Подключить","Понять"],
    solutionTag:"Наше первое внедрённое решение", solutionTitle:"Безопасный переход, который думает сам.", solutionText:"Умный пешеходный переход RIK обнаруживает людей у дороги, включает заметные предупреждающие сигналы и регистрирует каждое событие. Питание и связь настраиваются под конкретный объект.", checks:["Монтаж с учётом особенностей объекта","Надёжная работа в условиях северной зимы","Удалённый контроль состояния и эффективности"], discuss:"Обсудить внедрение", active:"Активное событие", detected:"Пешеход обнаружен · Сигналы включены", metrics:[["< 1 сек.","время реакции"],["24 / 7","удалённый контроль"],["Гибко","варианты питания"]],
    productsTag:"Расширяемый портфель продуктов", productsTitle:"Переход — это начало,|а не предел.", productsText:"RIK — платформенная компания. Новые подключённые продукты смогут использовать общую основу датчиков, связи и мониторинга.", current:"Уже внедрено", crossing:"Умный пешеходный переход", crossingText:"Активное обнаружение у дороги и яркое предупреждение для безопасных переходов.", future:"Место для будущего продукта", futureText:"Зарезервировано для следующего инфраструктурного решения RIK.",
    appsTag:"Создано для развития", appsTitle:"Одна платформа. Больше|возможностей для безопасных городов.", apps:[["Дорожные работы и временные зоны","Быстро развёртываемые предупреждения для меняющихся дорожных условий."],["Аналитика транспортных потоков","Распределённые датчики для обоснованных решений о мобильности."],["Периметр и общественная безопасность","Подключённый мониторинг важных общественных пространств."],["Экологический мониторинг","Удалённые сети измерения воздуха, шума и местных условий."]],
    monitorTag:"Централизованная аналитика", monitorTitle:"Знайте, что происходит.|До появления проблемы.", monitorText:"RIK Command объединяет все подключённые объекты в одном интерфейсе — от питания и качества сигнала до истории событий и обслуживания.", points:[["Статус сети в реальном времени","Все объекты с одного взгляда"],["Предиктивное обслуживание","Действуйте до остановки сервиса"],["Данные и отчётность","Превращайте события в полезную информацию"]], overview:"Обзор сети", region:"Рижский регион", update:"Обновлено: сейчас", activeDevices:"Активные устройства", thisWeek:"+2 за неделю", powerHealth:"Состояние питания", healthy:"В норме", events:"События сегодня", siteHealth:"Состояние объектов", online:"В сети", check:"Проверить", live:"Онлайн",
    contactTag:"Создавайте с RIK", contactTitle:"Инфраструктура должна быть|умной по умолчанию.", contactText:"Давайте определим, где подключённая инфраструктура принесёт наибольшую пользу вашей сети.", footer:"Связанный интеллект для безопасной инфраструктуры.",
  },
};
const ids = ["platform","solution","applications","monitoring"] as const;
const icons: LucideIcon[] = [Cpu, PlugZap, Radio, CloudCog];
const appIcons: LucideIcon[] = [TrafficCone, RouteIcon, ShieldCheck, Gauge];
const lines = (s:string) => { const [a,b]=s.split("|"); return <>{a}<br/>{b}</>; };
function AnchorButton({href,children,secondary=false}:{href:string;children:React.ReactNode;secondary?:boolean}) { return <a href={href} className={secondary?"button-secondary":"button-primary"}>{children}</a>; }
function LanguageSwitch({lang,setLang}:{lang:Lang;setLang:(l:Lang)=>void}) { return <div className="language-switch" aria-label="Language">{(["lv","en","ru"] as Lang[]).map(l=><button key={l} className={lang===l?"active":""} onClick={()=>setLang(l)} aria-pressed={lang===l}>{l.toUpperCase()}</button>)}</div>; }
function Header({t,lang,setLang}:{t:Copy;lang:Lang;setLang:(l:Lang)=>void}) { const [open,setOpen]=useState(false); return <header className="site-header"><div className="shell header-inner"><a href="#top" className="brand"><img src={logoAsset.url} alt="RIK Serviss"/></a><nav className="desktop-nav">{ids.map((id,i)=><a key={id} href={`#${id}`}>{t.nav[i]}</a>)}</nav><LanguageSwitch lang={lang} setLang={setLang}/><a href="#contact" className="header-cta">{t.contact}<ArrowRight size={16}/></a><button className="menu-button" aria-label={open?t.close:t.open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav className="mobile-nav">{ids.map((id,i)=><a key={id} href={`#${id}`} onClick={()=>setOpen(false)}>{t.nav[i]}</a>)}<LanguageSwitch lang={lang} setLang={setLang}/><a href="#contact" onClick={()=>setOpen(false)}>{t.contact}</a></nav>}</header>; }
function Eyebrow({children,light=false}:{children:React.ReactNode;light?:boolean}) { return <div className={`eyebrow ${light?"eyebrow-light":""}`}><span/>{children}</div>; }
function CityNetwork({t}:{t:Copy}) { return <div className="city-visual"><div className="visual-toolbar"><span><i/>{t.network}</span><span>{t.nodes}</span></div><svg viewBox="0 0 760 480"><defs><filter id="glow"><feGaussianBlur stdDeviation="4" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path className="map-line faint" d="M0 100L170 165L335 80L500 150L760 55M0 350L180 260L390 360L590 240L760 320"/><path className="road" d="M-20 410C135 315 240 350 365 245C480 148 560 154 790 65"/><path className="road-dash" d="M-20 410C135 315 240 350 365 245C480 148 560 154 790 65"/><path className="signal-line" d="M145 326L370 237L585 147"/><path className="signal-line delay" d="M370 237L622 338"/>{[[145,326],[370,237],[585,147],[622,338]].map(([x,y],i)=><g key={i} transform={`translate(${x} ${y})`}><circle className="node-pulse" r="22"/><circle className="node" r="8"/><circle className="node-core" r="3"/></g>)}<g transform="translate(322 188)"><rect className="hub" width="96" height="96" rx="16"/><path className="hub-mark" d="M34 25h28a4 4 0 0 1 4 4v24c0 12-9 19-18 23-9-4-18-11-18-23V29a4 4 0 0 1 4-4Z"/><text x="48" y="58" textAnchor="middle">R</text></g><g className="car" transform="translate(208 307) rotate(-19)"><rect x="-25" y="-12" width="50" height="24" rx="7"/><circle cx="-15" cy="14" r="5"/><circle cx="15" cy="14" r="5"/></g><g className="crossing" transform="translate(490 179) rotate(-32)">{[-36,-18,0,18,36].map(x=><rect key={x} x={x} y="-18" width="9" height="36" rx="2"/>)}</g></svg><div className="visual-label label-one"><Signal size={15}/><span>{t.lora}<br/><b>{t.long}</b></span></div><div className="visual-label label-two"><PlugZap size={15}/><span>{t.power}<br/><b>{t.powerModes}</b></span></div><div className="visual-stat"><b>99.8%</b><span>{t.uptime}</span></div></div>; }
function PlatformSection({t}:{t:Copy}) { return <section id="platform" className="section platform-section"><div className="shell"><div className="section-heading split-heading"><div><Eyebrow>{t.platformTag}</Eyebrow><h2>{lines(t.platformTitle)}</h2></div><p>{t.platformText}</p></div><div className="platform-grid">{t.layers.map(([title,text],i)=>{const Icon=icons[i]!;return <article className="platform-card" key={title}><div className="card-top"><span>0{i+1}</span><Icon/></div><h3>{title}</h3><p>{text}</p><div className="card-line"/></article>})}</div><div className="platform-flow"><span><Cpu/>{t.flow[0]}</span><ChevronRight/><span><Zap/>{t.flow[1]}</span><ChevronRight/><span><Radio/>{t.flow[2]}</span><ChevronRight/><span><Activity/>{t.flow[3]}</span></div></div></section>; }
function CrossingVisual({t}:{t:Copy}) { return <div className="crossing-visual"><div className="scene-sky"><div className="sun"><Sun/></div><div className="signal-waves"><i/><i/><i/></div></div><div className="scene-road"><div className="zebra">{Array.from({length:7}).map((_,i)=><i key={i}/>)}</div><div className="bollard left"><span/><b/></div><div className="bollard right"><span/><b/></div><div className="pedestrian"><i/><b/><em/><strong/></div></div><div className="scene-caption"><span className="live-dot"/>{t.active}<b>{t.detected}</b></div></div>; }
function SolutionSection({t}:{t:Copy}) { return <section id="solution" className="section solution-section"><div className="shell solution-grid"><div className="solution-copy"><Eyebrow light>{t.solutionTag}</Eyebrow><h2>{t.solutionTitle}</h2><p className="lead">{t.solutionText}</p><ul className="check-list">{t.checks.map(x=><li key={x}><CheckCircle2/>{x}</li>)}</ul><AnchorButton href="#contact">{t.discuss}<ArrowRight size={17}/></AnchorButton></div><div><CrossingVisual t={t}/><div className="metric-strip">{t.metrics.map(([a,b])=><div key={b}><b>{a}</b><span>{b}</span></div>)}</div></div></div></section>; }
function ApplicationsSection({t}:{t:Copy}) { return <section id="applications" className="section applications-section"><div className="shell"><div className="section-heading"><Eyebrow>{t.appsTag}</Eyebrow><h2>{lines(t.appsTitle)}</h2></div><div className="applications-grid">{t.apps.map(([title,text],i)=>{const Icon=appIcons[i]!;return <article key={title} className="application-item"><span className="application-index">0{i+1}</span><div className="icon-box"><Icon/></div><h3>{title}</h3><p>{text}</p><ArrowRight className="application-arrow"/></article>})}</div></div></section>; }
function MonitoringSection({t}:{t:Copy}) { return <section id="monitoring" className="section monitoring-section"><div className="shell monitoring-grid"><div className="monitor-copy"><Eyebrow>{t.monitorTag}</Eyebrow><h2>{lines(t.monitorTitle)}</h2><p>{t.monitorText}</p><div className="monitor-points">{[Activity,BatteryCharging,Network].map((Icon,i)=>{const p=t.points[i]!;return <div key={p[0]}><Icon/><span><b>{p[0]}</b>{p[1]}</span></div>})}</div></div><div className="dashboard"><div className="dashboard-top"><span><i/>RIK COMMAND</span><span>{t.live}</span></div><div className="dashboard-body"><div className="dash-side"><i/><i/><i/><i/></div><div className="dash-main"><div className="dash-title"><div><small>{t.overview}</small><b>{t.region}</b></div><span>{t.update}</span></div><div className="dash-stats"><div><span>{t.activeDevices}</span><b>48</b><em className="green">{t.thisWeek}</em></div><div><span>{t.powerHealth}</span><b>87%</b><em>{t.healthy}</em></div><div><span>{t.events}</span><b>1,284</b><em>↑ 12%</em></div></div><div className="dash-content"><div className="mini-map">{[[18,23],[35,57],[52,31],[70,68],[82,39]].map(([x,y],i)=><i key={i} style={{left:`${x}%`,top:`${y}%`}}/>)}<svg viewBox="0 0 300 130"><path d="M-10 100L70 58L120 78L200 25L310 62M20 0L75 52L110 140M180 0L205 30L250 140"/></svg></div><div className="sites"><span>{t.siteHealth}</span>{["Brīvības iela","Dzirnavu iela","Jūrmalas gatve"].map((x,i)=><div key={x}><i className={i===2?"amber":""}/><b>{x}</b><em>{i===2?t.check:t.online}</em></div>)}</div></div></div></div></div></div></section>; }
function ContactSection({t}:{t:Copy}) { return <section id="contact" className="contact-section"><div className="shell contact-inner"><div><Eyebrow light>{t.contactTag}</Eyebrow><h2>{lines(t.contactTitle)}</h2></div><div className="contact-action"><p>{t.contactText}</p><a href="mailto:info@rikserviss.lv" className="contact-link">info@rikserviss.lv<ArrowRight/></a></div></div></section>; }
function Footer({t}:{t:Copy}) { return <footer><div className="shell footer-inner"><a href="#top"><img src={logoAsset.url} alt="RIK Serviss"/></a><p>{t.footer}</p><div>{ids.slice(0,3).map((id,i)=><a key={id} href={`#${id}`}>{t.nav[i]}</a>)}</div><span>© {new Date().getFullYear()} RIK Serviss</span></div></footer>; }
function Index() { const [lang,setLangState]=useState<Lang>("en"); useEffect(()=>{const saved=window.localStorage.getItem("rik-language");const device=navigator.language.toLowerCase();const detected:Lang=saved==="lv"||saved==="ru"||saved==="en"?saved:device.startsWith("lv")?"lv":device.startsWith("ru")?"ru":"en";setLangState(detected);document.documentElement.lang=detected;},[]); const setLang=(next:Lang)=>{setLangState(next);window.localStorage.setItem("rik-language",next);document.documentElement.lang=next;}; useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add("is-visible")),{threshold:.12});document.querySelectorAll(".section-heading,.platform-card,.application-item,.solution-copy,.crossing-visual,.monitor-copy,.dashboard,.product-grid article").forEach(el=>observer.observe(el));return()=>observer.disconnect();},[lang]); const t=copy[lang]; return <main id="top"><Header t={t} lang={lang} setLang={setLang}/><section className="hero"><div className="hero-grid-bg"/><div className="shell hero-inner"><div className="hero-copy"><Eyebrow>{t.heroTag}</Eyebrow><h1>{t.heroA}<br/><span>{t.heroB}</span> {t.heroC}</h1><p>{t.heroText}</p><div className="hero-actions"><AnchorButton href="#platform">{t.explore}<ArrowRight size={17}/></AnchorButton><AnchorButton href="#solution" secondary>{t.first}</AnchorButton></div><div className="hero-proof"><span>{t.built}</span>{t.audiences.map((x,i)=><span className="proof-part" key={x}><b>{x}</b>{i<t.audiences.length-1&&<i/>}</span>)}</div></div><CityNetwork t={t}/></div><a href="#platform" className="scroll-cue"><span/>{t.scroll}</a></section><PlatformSection t={t}/><SolutionSection t={t}/><ApplicationsSection t={t}/><MonitoringSection t={t}/><ContactSection t={t}/><Footer t={t}/></main>; }
